steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/angular8-application/angular8-application", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/angular8-application/angular8-application"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "--allow-unauthenticated",
        "angular8-application",
        "--image",
        "gcr.io/angular8-application/angular8-application",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--memory",
        "128Mi"
      ]
images:
  - gcr.io/angular8-application/angular8-application